title: Yi Li's Personal Website
author:
  name: Yi Li
  email: YL808@georgetown.edu

theme: jekyll-theme-minimal

minima:
  skin: dark

minima:
  social_links:
    github: yili808
    linkedin: yi-li-808
